// JJKC OpenAI API 설정 파일

window.JJKC_OPENAI_CONFIG = {
  OPENAI_API_KEY: "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",
  OPENAI_MODEL: "gpt-5.5"
};
